# 빌드 스테이지
FROM openjdk:22-slim AS build

WORKDIR /app

# gradle 설정파일 복사
COPY gradlew gradle build.gradle settings.gradle ${WORKDIR}
COPY gradle/wrapper /app/gradle/wrapper

# 실행권한 부여 & build.gradle 의존성 다운로드
RUN chmod +x ./gradlew \
    && ./gradlew dependencies

# 소스코드 복사
COPY src /app/src

RUN ./gradlew clean build
# CMD ["tail", "-f"]
CMD ["./gradlew", "bootRun"]
