FROM nginx

RUN apt-get update && \
	apt-get install -y certbot python3-certbot-nginx && \
	rm /etc/nginx/conf.d/default.conf

# Copy files
COPY nginx.conf	/etc/nginx/
COPY tools/develop.conf	/etc/nginx/conf.d/

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
