FROM    nginx

# Install nginx
RUN	apt-get update
RUN     rm /etc/nginx/conf.d/default.conf

# Install certbot
RUN     apt-get update && \
        apt-get install -y certbot python3-certbot-nginx && \
        rm -f /etc/nginx/conf.d/default.conf

# Copy files
COPY	tools/develop.conf	/etc/nginx/conf.d/

# Start nginx
CMD		["nginx", "-g", "daemon off;"]
