server:
  tomcat:
    accept-count: 30
    max-connections: 8192
    threads:
      max: 30
spring:
  application:
    name: moheng
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moheng
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
oauth:
  kakao:
    authorize_uri: https://kauth.kakao.com/oauth/authorize
    redirect_uri: http://localhost:3000/callback/kakao
    client_secret: 3ZPJ93VC9MCuCXmPCDzrGmum2M3A7tif
    token_uri: https://kauth.kakao.com/oauth/token
    user_uri: https://kapi.kakao.com/v2/user/me
    client_id: 01bcd95738b16b4ab1a67945871afab7

security:
  jwt:
    token:
      secret_key: secretsecretsecretsecretsecretsecret
      expire_length:
        access_token: 36000000
        refresh_token: 36000000