global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "discord-notifications"

receivers:
  - name: "discord-notifications"
    discord_configs:
      - webhook_url: ${DISCORD_WEBHOOK_URL_PROMETHEUS}

# 심각도가 높은 경우 동일한 이름의 경고가 발생하지 않도록 설정
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
